version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: csv-profiler-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xmx2g -Xms1g
    volumes:
      - ./uploads:/app/uploads
    networks:
      - csv-profiler-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: csv-profiler-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - csv-profiler-network

networks:
  csv-profiler-network:
    driver: bridge

volumes:
  uploads: